replicaCount: 1

image:
  repository: ghcr.io/brieleon/anomaly-webapp
  tag: latest
  pullPolicy: Always
  pullSecrets:
    - name: ghcr-auth

 
serviceAccount:
  create: true
  name: ""
 
service:
  type: LoadBalancer
  ports:
    web:
      port: 8082
      targetPort: 8082

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: anomaly-detector.iobay.net
      paths:
        - path: /webapp
          pathType: Prefix
  tls:
    - secretName: anomaly-webapp-tls
      hosts:
        - anomaly-detector.iobay.net

env:
  REDIS_HOST: "anomaly-orchestrator-redis-master-master.anomaly-system.svc.cluster.local"
  REDIS_PORT: "6379"
